global:
  scrape_interval: "15s"
  external_labels:
    monitor: 'asa-gao-gao'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgatewaty'
    static_configs:
      - targets: ['localhost:9091']

rule_files:
- "/home/user/prometheus-2.3.2.linux-amd64/rule.yaml"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "ip:9093"
